name: Deploy preview na Vercel

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}

on: 
    push: 
        branches-ignore: 
            - master

jobs:
    Deploy-Preview:
        runs-on: ubuntu-latest
        steps:
            
            - uses: actions/checkout@v3

            - name: Install Vercel CLI 
              run: npm install --global vercel

            - name: Adicionar informações de ambiente vercel
              run: vercel pull --yes --enviroment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel run --token=${{ secrets.VERCEL_TOKEN }}
            
            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
              
